services:
  api:
    build: .
    container_name: guardiao-api
    volumes:
      - ./app:/app            
    working_dir: /app         
    ports:
      - "3001:3000"
    depends_on:
      - mysql
      - redis
    environment:
      DATABASE_URL: mysql://root:root@mysql:3306/guardiao_db

  mysql:
    image: mysql:8
    container_name: guardiao-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: guardiao_db
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7
    container_name: guardiao-redis
    ports:
      - "6379:6379"

  adminer:
    image: adminer
    container_name: guardiao-adminer
    ports:
      - "8080:8080"

volumes:
  mysql_data:
